services:
  capellania-db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: capellania_dev
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      MIX_TEST_PARTITION: dev
    ports:
      - "5432:5432"

  capellania-api:
    build: .
    depends_on:
      - capellania-db
    environment:
      MIX_ENV: dev
      DB_HOST: capellania
      DB_NAME: capellania_dev
      DB_USER: admin
      DB_PASS: admin
    ports:
      - "5000:5000"

#    volumes:
#     - .:/app

volumes:
  postgres_data:
