# Usa una imagen base oficial de Node.js
FROM node:14

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias del proyecto
RUN npm install

# Copia el resto de la aplicación en el contenedor
COPY . .

# Exponer el puerto en el que corre la aplicación
EXPOSE 5000

# Comando para correr la aplicación
CMD ["node", "server.js"]
